#!/bin/bash

#DMN_NEW=idc2vm68-mydb02
#DMN_NEW_VMHOST=idc2vm68
#DMN_NEW_IP=192.168.203.202
#DMN_NEW_VOLUME=G

XMLPATH="/etc/libvirt/qemu"
XMLFILE=${DMN_NEW}.xml
XMLDMN="${XMLPATH}/${XMLFILE}"
UPPER_VMHOST=`echo ${DMN_NEW_VMHOST}|tr [a-z] [A-Z]`
DMN_NEW_IF=`echo ${DMN_NEW_IP}|cut -f3 -d.`

cat /dev/null > ${XMLDMN}

echo "<domain type='kvm'>" >> ${XMLDMN}
echo "  <name>${DMN_NEW}</name>" >> ${XMLDMN}
echo "  <memory unit='KiB'>4194304</memory>" >> ${XMLDMN}
echo "  <currentMemory unit='KiB'>4194304</currentMemory>" >> ${XMLDMN}
echo "  <vcpu placement='static' current='2'>32</vcpu>" >> ${XMLDMN}
echo "  <os>" >> ${XMLDMN}
echo "    <type arch='x86_64'>hvm</type>" >> ${XMLDMN}
echo "    <boot dev='hd'/>" >> ${XMLDMN}
echo "  </os>" >> ${XMLDMN}
echo "  <features>" >> ${XMLDMN}
echo "    <acpi/>" >> ${XMLDMN}
echo "    <apic/>" >> ${XMLDMN}
echo "    <pae/>" >> ${XMLDMN}
echo "  </features>" >> ${XMLDMN}
echo "  <clock offset='utc'/>" >> ${XMLDMN}
echo "  <on_poweroff>destroy</on_poweroff>" >> ${XMLDMN}
echo "  <on_reboot>restart</on_reboot>" >> ${XMLDMN}
echo "  <on_crash>restart</on_crash>" >> ${XMLDMN}
echo "  <devices>" >> ${XMLDMN}
echo "    <emulator>/usr/libexec/qemu-kvm</emulator>" >> ${XMLDMN}
echo "    <disk type='file' device='disk'>" >> ${XMLDMN}
echo "      <driver name='qemu' type='raw' cache='none'/>" >> ${XMLDMN}
echo "      <source file='/var/lib/libvirt/images/${DMN_NEW_VOLUME_POOL_SYSTEM}/${DMN_NEW}.img'/>" >> ${XMLDMN}
echo "      <target dev='vda' bus='virtio'/>" >> ${XMLDMN}
echo "    </disk>" >> ${XMLDMN}
echo "    <disk type='file' device='cdrom'>" >> ${XMLDMN}
echo "      <driver name='qemu' type='raw'/>" >> ${XMLDMN}
echo "      <target dev='hda' bus='ide'/>" >> ${XMLDMN}
echo "      <readonly/>" >> ${XMLDMN}
echo "    </disk>" >> ${XMLDMN}
echo "    <interface type='bridge'>" >> ${XMLDMN}
echo "      <source bridge='bri_${DMN_NEW_IF}'/>" >> ${XMLDMN}
echo "      <model type='virtio'/>" >> ${XMLDMN}
echo "    </interface>" >> ${XMLDMN}
echo "    <graphics type='vnc' port='-1' autoport='yes'/>" >> ${XMLDMN}
echo "    <video>" >> ${XMLDMN}
echo "      <model type='cirrus' vram='9216' heads='1'/>" >> ${XMLDMN}
echo "    </video>" >> ${XMLDMN}
echo "    <memballoon model='virtio'>" >> ${XMLDMN}
echo "    </memballoon>" >> ${XMLDMN}
echo "  </devices>" >> ${XMLDMN}
echo "</domain>" >> ${XMLDMN}

virsh define ${XMLDMN}

